# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$os\
[ ](bg:color_blue fg:color_white)\
$directory\
${custom.git} \
"""

right_format = """
$status\
[](fg:color_white)\
$time\
$aws\
$c\
$cpp\
$java\
$python\
$rust\
$cmd_duration\
"""

continuation_prompt = '▶▶ '

palette = 'my_colors'

[palettes.my_colors]
color_white = '#ffffff'
color_black = '#000000'
color_blue = '#1d99f3'
color_green = '#11d116'
color_orange = '#f67400'
color_grey = '#9e9e9e'
color_c = '#585858'
color_java = '#0f6aa8'
color_rust = '#f94b00'

[os]
disabled = false
style = "bold bg:color_white fg:color_black"
format = "[ $symbol ]($style)"

[os.symbols]
Amazon = ""
Arch = "󰣇"
Debian = "󰣚"
Ubuntu = "󰕈"
CentOS = ""
Linux = "󰌽"

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1
use_os_path_sep = true
style = "bg:color_blue fg:color_white"
format = "[$path]($style)"

[custom.git]
description = "git status which calls git directly"
when = true
require_repo = true
command = "bash ~/.config/starship/starship-git.sh"
format = "$output"
disabled = false

[time]
disabled = false
time_format = "%T"
style = "fg:color_black bg:color_white"
format = '[ $time ]($style)'

[cmd_duration]
min_time = 1_000
show_milliseconds = false
style = "fg:color_black bg:color_grey"
format = '[ took $duration]($style)'

# TODO: Do not have the status (exit code) when the command was a success.
[status]
disabled = false
format = '[$status $symbol]($style) '
symbol = '✘'
success_symbol = '✔'
success_style = "green"

# Languages
[c]
symbol = "ℂ"
style = "bg:color_c"
format = '[[](bg:color_white fg:color_c)$symbol $name $version ]($style)'

[cpp]
symbol = "ℂ"
style = "bg:color_c"
format = '[[](bg:color_white fg:color_c)$symbol $name $version ]($style)'
disabled = false

[java]
symbol = ""
style = "bg:color_java"
format = '[[](bg:color_white fg:color_java)$symbol $version ]($style)'

[python]
symbol = ""
style = "bg:color_green fg:color_black"
format = '[[](bg:color_white fg:color_green)$symbol $version ]($style)'

[rust]
version_format = 'v${major}.${minor}'
symbol = ""
style = "bg:color_rust"
format = '[[](bg:color_white fg:color_rust)$symbol $version ]($style)'
