theme = "darcula"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = true

[keys.normal]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]
esc = ["collapse_selection", "keep_primary_selection"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
d = { d = ["extend_to_line_bounds", "delete_selection"] }
V = ["select_mode", "extend_to_line_bounds"]
