theme = "darcula"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
d = { d = ["extend_to_line_bounds", "delete_selection"] }

[editor.cursor-shape]
insert = "bar"
