theme = "darcula"

[editor]
line-number = "relative"
bufferline = "multiple"
auto-pairs = false
mouse = true
# scrolloff = 999  # always center cursor on screen.

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
# The options below are not working...
hidden = false
git-ignore = false
ignore = false
git-global = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Movements
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
G = "goto_last_line"

# Search
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]

# Deletion
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
d = { d = ["extend_to_line_bounds", "delete_selection"] }
# x = ["delete_selection", "move_char_left"]

# Other
V = ["select_mode", "extend_to_line_bounds"]
y = { y = ["extend_to_line_bounds", "yank", "collapse_selection"] }

# Config, these don't work either...
# backspace = { s = [":w", ":config-reload"]}
# backspace = { c = [":config-open"]}
