name: Lint Spelling

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    paths:
      - "**.py"
      - "**.md"
      - "**.toml"
      - "**.yaml"
      - .github/workflows/lint-spelling.yaml
      - pyproject.toml
      - uv.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  spelling-lint:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use custom config file
        uses: crate-ci/typos@v1.44.0
        with:
          config: .config/typos/typos.toml
